/**
 * Copyright (C), 2026-02-05
 * @author ZestBox
 * @date 2026/02/05
 * @version 1.0
 * @description: 路由器url常量
 */

const TAG: string = '[RouterUrlConstants]';

export class RouterUrlConstants {
  /**
   * 主页
   */
  static readonly HOME: string = 'Home';
  /**
   * 账单
   */
  static readonly BILLING: string = 'Billing';
  /**
   * 报表
   */
  static readonly REPORTS: string = 'Reports';
  /**
   * 我的
   */
  static readonly PROFILE: string = 'Profile';
  /**
   * 日常
   */
  static readonly ORDINARY: string = 'Ordinary';
  /**
   * 资产
   */
  static readonly ASSETS: string = 'Assets';

}